### PR TITLE
Add CircleCI integration

### LINKED ISSUE #9: Set up CI
It would be great to set up Travis or CircleCI to automate the blacking of the code and the unit tests.

### PR DESCRIPTION
**Pull request by platipo**
Fixes #9

### CODE REVIEW

**Comment by johannesjmeyer** [comment]
I just set up CircleCI with a rudimentary pytest execution, just to get it up and running. Feel free to change everything!
There seem to be some pre-existing packages that we can look at for guidance, or use them directly, e.g. [here](https://circleci.com/developer/orbs/orb/dialogue/python)

**Comment by platipo** [comment]
I rebased the branch onto your commits and noticed that CircleCI has not triggered any build. I suspect that the build is not activated for PRs, can you verify it? ([link](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories) to read more)

**Comment by johannesjmeyer** [comment]
I enabled building forked PRs, thanks for pointing that out! Maybe you have to add another commit or undraft the PR to trigger Circle CI

**Comment by johannesjmeyer** [comment]
Also please add yourself to the Contributor section of the readme!

**Comment by johannesjmeyer** [comment]
You have to merge with master to get the requirements.txt! I also had to add that one when I was setting up CircleCI in the first place

**Comment by platipo** [comment]
I got the first build compiling! :confetti_ball:  

The lint job is failing because there are actual linting warnings raised.

Don't worry about the requirements I already rebased the branch onto your master to align!

**Comment by platipo** [comment]
The pipeline now is the following, where black, lint and build run in parallel and if build passes it'll run test:
pipeine
Do you want me to add a black and lint as a requirement to build?

**Comment by platipo** [comment]
@johannesjmeyer do you want me to add other things?

**Comment by johannesjmeyer** [comment]
Thanks a ton already, this is really great and great help! If you still have some time to spare, then setting up a code coverage service would be great. It seems like you can do that via CircleCI, but I only ever worked on repos that depended on codecov (which didn't work so well actually...). 

And it would be great to run black with `-l 100` as this is the default setting I'm used to now from pennylane development. 

Other than that I'm more than happy!

**Comment by platipo** [comment]
> If you still have some time to spare, then setting up a code coverage service would be great

Do you have any coverage service in mind?

> And it would be great to run black with -l 100 as this is the default setting I'm used to now from pennylane development.

Just `black -l 100`?

**Comment by johannesjmeyer** [comment]
Not really. If think it would be best if we get it running with CircleCI, there seems to be a python package for that (coverage.py) which we can invoke. 

Just add the additional `-l 100` to the current options!

**Comment by platipo** [comment]
> Not really. If think it would be best if we get it running with CircleCI, there seems to be a python package for that (coverage.py) which we can invoke.

If you want I can store the coverage files as artifacts (they will be accessible for 30 days after creation)

**Comment by johannesjmeyer** [comment]
That would be great!

**Comment by platipo** [comment]
All done! :smile: 
You can navigate coverage [here](https://app.circleci.com/pipelines/github/johannesjmeyer/rsmf/20/workflows/7b6b18bc-1c93-4ff0-81c5-9d655c7e8295/jobs/57/artifacts) (via index.html) and I also tracked tests in CircleCI [here](https://app.circleci.com/pipelines/github/johannesjmeyer/rsmf/20/workflows/7b6b18bc-1c93-4ff0-81c5-9d655c7e8295/jobs/57/tests).

Also also the CircleCI badge in the README was added (it can be customized with a different [style](https://circleci.com/docs/2.0/status-badges/#different-styles)).

**Comment by johannesjmeyer** [comment]
Amazing! Thanks a lot! I will merge it then.

I've seen that you used the classicthesis latex document class. Would you fancy adding support for that to rsmf? In principle I can also do it if you describe to me how you use it.

**Comment by platipo** [comment]
Thank you! I have one last favor to ask you: can you add the `hacktoberfest-accepted` label to this PR?

I kept the classicthesis repository even though nowadays I don't use LaTeX anymore (sadly) and it has become an out-of-date fork. 

I am probably out of shape with my LaTeX, but if you want to add rsmf to classicthesis I'll happily help you!

**Comment by johannesjmeyer** [comment]
Is it okay this way? Really appreciate your help!

Okay, then never mind, I take care of it myself :)

**Comment by platipo** [comment]
Yeah, it works!

I almost forgot to tell you one thing: you can reduce the duplication of the requirements by replacing in the `setup.py`:
```python
requirements = [
    "matplotlib",
]
```
with:
```python
with open('requirements.txt') as f:
    requirements = f.read().splitlines()
```
so you can track your dependencies in only one place.

**Pull request merged**
